name: Build TrollStore

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Install dependencies
      run: |
        brew install make
        brew install ldid
        brew install xz
        brew install dpkg
        brew install openssl
        
    - name: Setup environment
      run: |
        export THEOS=${{ github.workspace }}/theos
        export PATH="/opt/homebrew/bin:$PATH"
        export PKG_CONFIG_PATH="/opt/homebrew/lib/pkgconfig:$PKG_CONFIG_PATH"
        export CFLAGS="-I/opt/homebrew/include -I$THEOS/include -Wno-error=unused-variable"
        export LDFLAGS="-L/opt/homebrew/lib -L$THEOS/lib"
        echo "THEOS=$THEOS" >> $GITHUB_ENV
        echo "PATH=$PATH" >> $GITHUB_ENV
        echo "PKG_CONFIG_PATH=$PKG_CONFIG_PATH" >> $GITHUB_ENV
        echo "CFLAGS=$CFLAGS" >> $GITHUB_ENV
        echo "LDFLAGS=$LDFLAGS" >> $GITHUB_ENV
        
    - name: Setup Theos
      run: |
        git clone --recursive https://github.com/theos/theos.git $THEOS
        mkdir -p $THEOS/sdks
        curl -LO https://github.com/theos/sdks/archive/master.zip
        unzip -o master.zip
        mv sdks-master/*.sdk $THEOS/sdks/
        rm -rf master.zip sdks-master
        
    - name: Setup Private Frameworks
      run: |
        mkdir -p ${{ github.workspace }}/theos/lib
        cd ${{ github.workspace }}/theos/lib
        curl -LO https://github.com/theos/lib/archive/master.zip
        unzip -o master.zip
        cp -R lib-master/* ./
        rm -rf master.zip lib-master
        
    - name: Build fastPathSign
      run: |
        cd Exploits/fastPathSign
        make
        chmod +x fastPathSign
        cd ../..
        
    - name: Build TrollStore
      run: |
        cd TrollStore
        make package THEOS_PACKAGE_SCHEME=rootless
        
    - name: Build TrollHelper
      run: |
        cd TrollHelper
        make package THEOS_PACKAGE_SCHEME=rootless
        
    - name: Build PersistenceHelper
      run: |
        cd PersistenceHelper
        make package THEOS_PACKAGE_SCHEME=rootless
        
    - name: Create TrollStore Package
      run: |
        mkdir -p package/TrollStore.app
        cp -r TrollStore/.theos/obj/debug/* package/TrollStore.app/
        cp -r TrollHelper/.theos/obj/debug/* package/TrollStore.app/
        cp -r PersistenceHelper/.theos/obj/debug/* package/TrollStore.app/
        cd package
        tar -czf TrollStore.tar TrollStore.app
        
    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: TrollStore
        path: package/TrollStore.tar
        retention-days: 5
