name: Build TrollStore

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Install Theos
      run: |
        brew install ldid
        git clone --recursive https://github.com/theos/theos.git $THEOS
        brew install make
        brew install dpkg
        brew install xz
      env:
        THEOS: /usr/local/theos
        
    - name: Install iOS SDK
      run: |
        curl -LO https://github.com/theos/sdks/archive/master.zip
        unzip master.zip -d $THEOS/sdks
        mv $THEOS/sdks/sdks-master/*.sdk $THEOS/sdks/
        rm -rf master.zip $THEOS/sdks/sdks-master
      env:
        THEOS: /usr/local/theos
        
    - name: Build Project
      run: |
        make package
      env:
        THEOS: /usr/local/theos
        
    - name: Create TrollStore Package
      run: |
        mkdir -p package/TrollStore.app
        cp -r .theos/obj/debug/* package/TrollStore.app/
        cd package
        tar -czf TrollStore.tar TrollStore.app
        
    - name: Upload Artifact
      uses: actions/upload-artifact@v2
      with:
        name: TrollStore
        path: package/TrollStore.tar
