name: Build TrollStore

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Install Theos
      run: |
        brew install ldid
        mkdir -p $HOME/theos
        git clone --recursive https://github.com/theos/theos.git $HOME/theos
        brew install make
        brew install dpkg
        brew install xz
      env:
        THEOS: ${{ github.workspace }}/theos
        
    - name: Install iOS SDK
      run: |
        curl -LO https://github.com/theos/sdks/archive/master.zip
        unzip master.zip -d $THEOS/sdks
        mv $THEOS/sdks/sdks-master/*.sdk $THEOS/sdks/
        rm -rf master.zip $THEOS/sdks/sdks-master
      env:
        THEOS: ${{ github.workspace }}/theos
        
    - name: Build Project
      run: |
        export PATH="/opt/homebrew/bin:$PATH"
        export THEOS=${{ github.workspace }}/theos
        make package
        
    - name: Create TrollStore Package
      run: |
        mkdir -p package/TrollStore.app
        cp -r .theos/obj/debug/* package/TrollStore.app/
        cd package
        tar -czf TrollStore.tar TrollStore.app
        
    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: TrollStore
        path: package/TrollStore.tar
        retention-days: 5
