name: Build TrollStore

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Theos
      run: |
        export THEOS=${{ github.workspace }}/theos
        brew install ldid make dpkg xz
        git clone --recursive https://github.com/theos/theos.git $THEOS
        mkdir -p $THEOS/sdks
        curl -LO https://github.com/theos/sdks/archive/master.zip
        unzip -o master.zip
        mv sdks-master/*.sdk $THEOS/sdks/
        rm -rf master.zip sdks-master
        
    - name: Build Project
      run: |
        export PATH="/opt/homebrew/bin:$PATH"
        export THEOS=${{ github.workspace }}/theos
        make package
        
    - name: Create TrollStore Package
      run: |
        mkdir -p package/TrollStore.app
        cp -r .theos/obj/debug/* package/TrollStore.app/
        cd package
        tar -czf TrollStore.tar TrollStore.app
        
    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: TrollStore
        path: package/TrollStore.tar
        retention-days: 5
