name: Unzip Files

on:
  push:
    paths:
      - '**.zip'
  workflow_dispatch:

jobs:
  unzip:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        
      - name: Configure Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          
      - name: Unzip and Move Files
        run: |
          for zip in *.zip; do
            if [ -f "$zip" ]; then
              echo "Unzipping $zip"
              # 创建临时目录
              mkdir -p temp_dir
              # 解压到临时目录
              unzip -o "$zip" -d temp_dir
              # 移动文件到根目录
              mv temp_dir/TrollStore-main/* .
              # 清理
              rm -rf temp_dir
              rm "$zip"
            else
              echo "No zip files found"
            fi
          done
          
      - name: Commit and push changes
        run: |
          git add -A
          git status
          git commit -m "Add TrollStore files" || echo "No changes to commit"
          git push origin HEAD:main || echo "No changes to push"
