name: Unzip Files

on:
  push:
    paths:
      - '**.zip'
  workflow_dispatch:

jobs:
  unzip:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Unzip Files
        run: |
          for zip in *.zip; do
            if [ -f "$zip" ]; then
              unzip -o "$zip"
              rm "$zip"
            fi
          done
          
      - name: Setup Git
        run: |
          git config --global user.name "lengye666"
          git config --global user.email "${{ secrets.GIT_EMAIL }}"
          
      - name: Commit & Push changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PAT: ${{ secrets.PAT }}
        run: |
          git add -A
          git commit -m "Unzip files" || echo "No changes to commit"
          git remote set-url origin "https://${{ secrets.PAT }}@github.com/${GITHUB_REPOSITORY}.git"
          git push origin HEAD:${GITHUB_REF#refs/heads/}
